# Name of this GitHub Actions workflow.
name: Semgrep Diff-Aware and Mainline Scanning

on:
  # Scan changed files in PRs (diff-aware scanning):
  pull_request: {}
  # Scan on-demand through GitHub Actions interface:
  workflow_dispatch: {}
  # Scan mainline branches and report all findings:
  push:
    branches: ["master", "main"]
  paths-ignore:
      - '.github/workflows/Semgrep-Mainline+Diff.yml'

permissions:
  # required for all workflows
  security-events: write
  # for workflows in private repos
  actions: read
  contents: read

jobs:
  semgrep:
    # User definable name of this GitHub Actions job.
    name: semgrep/ci
    # If you are self-hosting, change the following `runs-on` value:
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep
        run: |
          # Copy the event.json file into the current working directory 
          # so it gets mounted when we run docker and semgrep can refer 
          # to it to auto-magically set git metadata.
          cp $GITHUB_EVENT_PATH ./.github_event_path.json
          # Copy over all GitHub Actions related env vars from the runner
          # environment into a file that will get passed into docker so 
          # we retain all necessary env vars that semgrep uses for 
          # auto-magically setting git metadata.
          echo "Saving these env vars to file, then passing into docker container."
          printenv | sort | egrep "^GITHUB_" | tee .env
          printenv | sort | egrep "^RUNNER_" | tee -a .env
          # Recursively set the owner:group of all files in the current
          # working directory to the UID and GID of the semgrep user
          # that the non-root semgrep docker image runs as. When we bind
          # mount the directory to our docker container, it retains the
          # permissions of the host.
          sudo chown -R 1000:1000 .
          # Finally, we pass in all the env vars from our file along with
          # setting the SEMGREP_APP_TOKEN and updated GITHUB_EVENT_PATH.
          docker run --rm -v "${PWD}:/src" \
            --env-file .env \
            -e SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }} \
            -e GITHUB_EVENT_PATH="/src/.github_event_path.json" \
            returntocorp/semgrep:latest-nonroot \
            semgrep ci --sarif > semgrep.sarif

      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
        if: always()
